### ISSUE TITLE
TwillPackageServiceProvider not found on composer require

### ISSUE THREAD

**Issue by paperscissors** [Sevendays-Digital/twill-redirects#1]
Using PHP 8.1, Twill 2.6 when I do a composer require for this package I get the following error when composer runs scripts at the end. It happens when trying to run any subsequent Laravel functionality as well. Is it using the wrong service provider filename, perhaps? Closest thing I see in the Twill vendor directory is `TwillServiceProvider`.

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In TwillRedirectsServiceProvider.php line 7:
                                                           
  Class "A17\Twill\TwillPackageServiceProvider" not found  
                                                           
```

**Comment by haringsrob** [comment]
Hey @paperscissors this is only compatible with twill 2.8

**Comment by haringsrob** [comment]
I should fix that in the composer.json sorry about that.
